### ISSUE TITLE
phpstorm 2020.1 plugin error

### ISSUE THREAD

**Issue by IsaacHub** [mikinw/StickySelection#24]
```
Should be called at least in the state COMPONENTS_LOADED, the current state is: CONFIGURATION_STORE_INITIALIZED
Current violators count: 1

java.lang.Throwable
	at com.intellij.diagnostic.LoadingState.logStateError(LoadingState.java:56)
	at com.intellij.diagnostic.LoadingState.checkOccurred(LoadingState.java:52)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.<init>(ActionManagerImpl.java:150)
```

**Comment by mikinw** [comment]
Same as #26 
Should be fixed soon
